# Generated by Django 5.1.8 on 2026-03-30 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('strength', models.CharField(blank=True, max_length=64)),
                ('dosage_form', models.CharField(blank=True, max_length=64)),
                ('route', models.CharField(blank=True, max_length=64)),
                ('indication', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('meal_relation', models.CharField(choices=[('before_meal', 'Before Meal'), ('after_meal', 'After Meal'), ('with_meal', 'With Meal'), ('independent', 'Independent')], default='independent', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low_stock_threshold_days', models.PositiveIntegerField(default=5)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('dose_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('recurrence_type', models.CharField(choices=[('daily', 'Daily'), ('specific_days', 'Specific Days'), ('weekly', 'Weekly'), ('alternate_days', 'Alternate Days'), ('prn', 'As Needed')], default='daily', max_length=20)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='care.medication')),
            ],
            options={
                'ordering': ('time_of_day', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Undisclosed')], default='undisclosed', max_length=16)),
                ('conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('voice_reminders_enabled', models.BooleanField(default=False)),
                ('large_text_mode', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_record', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='care.patient'),
        ),
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField()),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('skipped', 'Skipped'), ('snoozed', 'Snoozed'), ('missed', 'Missed')], default='taken', max_length=20)),
                ('source', models.CharField(choices=[('app', 'App'), ('whatsapp', 'WhatsApp'), ('ivr', 'IVR'), ('caregiver', 'Caregiver'), ('provider', 'Provider'), ('system', 'System')], default='app', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dose_logs', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='care.medication')),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dose_logs', to='care.medicationreminder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='care.patient')),
            ],
            options={
                'ordering': ('-scheduled_for',),
            },
        ),
        migrations.CreateModel(
            name='PrescriptionUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='prescriptions/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('needs_clarification', 'Needs Clarification')], default='pending', max_length=32)),
                ('ocr_text', models.TextField(blank=True)),
                ('extracted_payload', models.JSONField(blank=True, default=dict)),
                ('review_notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='care.patient')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='care.prescriptionupload'),
        ),
        migrations.CreateModel(
            name='CaregiverRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('child', 'Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('parent', 'Parent'), ('other', 'Other')], default='other', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('receives_missed_dose_alerts', models.BooleanField(default=True)),
                ('receives_refill_alerts', models.BooleanField(default=True)),
                ('receives_weekly_summary', models.BooleanField(default=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_relationships', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_relationships', to='care.patient')),
            ],
            options={
                'ordering': ('-is_primary', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('patient', 'caregiver'), name='unique_patient_caregiver_relationship')],
            },
        ),
        migrations.CreateModel(
            name='ProviderAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_role', models.CharField(choices=[('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('nurse', 'Nurse'), ('care_coordinator', 'Care Coordinator')], default='doctor', max_length=32)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('can_view_full_medication_list', models.BooleanField(default=True)),
                ('can_manage_medications', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_relationships', to='care.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('organization', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('patient', 'provider', 'provider_role'), name='unique_patient_provider_access')],
            },
        ),
    ]
